### ISSUE TITLE
java.util.zip.ZipException: EOCD record not found in last 32k of archive, giving up

### ISSUE THREAD

**Issue by keshav0891** [andrewhayden/archive-patcher#13]
Getting above exception while using tar.gz file of size 81MB. 
I tried changing the file permissions but it didn't help. 
Is there a size limitation with current implementation? Any other leads are appreciable. Thanks.

StackTrace:
`Exception in thread "main" java.util.zip.ZipException: EOCD record not found in last 32k of archive, giving up
	at com.google.archivepatcher.generator.MinimalZipArchive.listEntriesInternal(MinimalZipArchive.java:72)
	at com.google.archivepatcher.generator.MinimalZipArchive.listEntries(MinimalZipArchive.java:56)
	at com.google.archivepatcher.generator.PreDiffExecutor.generatePreDiffPlan(PreDiffExecutor.java:210)
	at com.google.archivepatcher.generator.PreDiffExecutor.prepareForDiffing(PreDiffExecutor.java:157)
	at com.google.archivepatcher.generator.FileByFileV1DeltaGenerator.generateDelta(FileByFileV1DeltaGenerator.java:81)
	at com.google.archivepatcher.sample.SamplePatchGenerator.main(SamplePatchGenerator.java:41)`

**Comment by andrewhayden** [comment]
ArchivePatcher only works on archives. Gzip files are not *archives*. They are compressed individual files. To illustrate the point:

* You can zip up an entire directory. Within the resulting ZIP archive, you will find individual records representing each directory as well as each file within those directories, including things like the last-modified time and date, comments, etc, along with the compressed bytes. This is an archive.

* By contrast, you gzip a single file. Within the gzip file you will find a checksum for the uncompressed data, some headers containing metadata about that specific file, and its compressed bytes. This is just one file, compressed.

You could consider a gzip file a degenerate case of an archive, in that it contains one entry. But it isn't a ZIP file. There is no central directory (thus the error you saw, which results from searching for an end-of-central-directory marker called EOCD).

It's possible that gz support could be added in a future iteration, but I think it is unlikely. This would require a bunch of gzip-specific logic, since gzip headers are not the same as zip headers, and regression testing against a bunch of gzip implementations to test their deflate compatibility.

I'm going to resolve this since it is not a bug, and since the library doesn't support this functionality. But we should probably update the docs to make it clearer that gzip is not an archive format.

Gzip's homepage discusses this a little bit more here, so you can see it is not the intent of gzip to support archives:
http://www.gzip.org/#faq16

**Comment by andrewhayden** [comment]
As a workaround, if you have flexibility, you can simply zip the file you want to generate patches on instead of gzip'ing it. It is every so slightly less efficient because there is extra overhead in the zip metadata, but with your resource being 81mb you shouldn't notice (we're talking on the order of a few tens of bytes).
