### ISSUE TITLE
cpp/object-c implementation?

### ISSUE THREAD

**Issue by kaedea** [andrewhayden/archive-patcher#15]
Thanks for this repo, before which we use bsdiff while archive-diff works much better with zip files. The problem is that we have clients of both Android and iOS, and it is not a bad idea to do the same diff and patch jobs within both platforms.

However, I can not find any similar implementation with cpp/object-c. Could anyone offer a way? I am trying to translate the patching job with my poor cpp.

**Comment by andrewhayden** [comment]
I am not aware of any plans to port this library to C or C++, but it is certainly possible since zlib, the deflate library, is certainly available in those languages as well (and since both the Android Open Source Project and the Open JDK use the same library, it shouldn't be a problem from a compatibility standpoint).

Note that you could generate in Java (server-side, presumably most servers can run Java if needed) and apply in C/C++.

You are of course free to implement your own patch applier in C++ that is compatible with the patch format, which is described in full detail in the [README](https://github.com/andrewhayden/archive-patcher/blob/master/README.md#the-file-by-file-v1-patch-format), The patch _applier_ is far less complex than the patch _generator_. The logic is simpler and more straightforward because all the hard work of planning and generating the patch has been done already.

The [FileByFileV1DeltaApplier](https://github.com/andrewhayden/archive-patcher/blob/master/applier/src/main/java/com/google/archivepatcher/applier/FileByFileV1DeltaApplier.java) is the best starting place to understand what you need to do. If you follow the workflow in that class down into all the other various classes it uses, you will find 100% of the logic required to apply a patch and you can then either implement something compatible on your own or attempt a straight C/C++ port of the class structure, as you see fit.

Good luck!

**Comment by andrewhayden** [comment]
Quick additional note - if re-implementing do be aware that although bsdiff is used as the delta algorithm, it has been stripped of its normal bzip compression. I opened a new issue to update the README documentation to make this clearer to anyone else trying to do something similar ([issue 16](https://github.com/andrewhayden/archive-patcher/issues/16)).

**Comment by kaedea** [comment]
Thanks for the support above. There is enough info.
