### ISSUE TITLE
Support For iOS

### ISSUE THREAD

**Issue by effectivecui** [andrewhayden/archive-patcher#155]
Thanks for archive-patcher. It solved my problem on Android. Now , I want to use archive-patcher on iOS, I want to know whether there is a brother project that could support me.

**Comment by andrewhayden** [comment]
I'm not aware of any such project, but that doesn't mean there isn't one. The patch format is, of course, completely operating-system agnostic... so in principle, an iOS-compatible Swift or Objective-C implementation of a patch applier should be pretty straightforward, assuming that the zlib versions shipped with the patch applier and/or the operating system are compatible.

Since the patch format is cleanly and completely documented in the [README.md](https://github.com/google/archive-patcher/blob/master/README.md) it's possible to create a completely independent implementation of a patch applier. Porting from Java should be reasonably straightforward as all the necessary sources are here. You could also try https://github.com/google/j2objc but I've never personally given it a shot, your mileage may vary.

**Comment by effectivecui** [comment]
thanks for your reply @andrewhayden
